### ISSUE TITLE
Fix python dependency to include `python=3.9`

### ISSUE THREAD

**Issue by sgreenbury** [alan-turing-institute/learning-machines-drift#26]
Currently dependency specified as:
```toml
[tool.poetry.dependencies]
python = ">3.9,<3.10"
```
Installation is currently failing and should be updated to include `python=3.9`:
```toml
[tool.poetry.dependencies]
python = ">=3.9,<3.10"
```
